export const stories = [
  {
    id: 1,
    title: 'Rise of the Forgotten Realm',
    slug: 'rise-of-the-forgotten-realm',
    lastEdited: '2024-07-10',
    isPublic: true,
    status: 'published',
    rating: 'GENERAL',
    genres: ['Fantasy', 'Adventure'],
    stats: { chapters: 12, branches: 4, avgRating: 4.2 },

    coverImage: '',
    description: '',
    totalChapters: 12,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 2,
    title: 'Shadows of Crimson City',
    slug: 'shadows-of-crimson-city',
    lastEdited: '2024-07-12',
    isPublic: false,
    status: 'draft',
    rating: 'TEEN',
    genres: ['Action', 'Sci-Fi'],
    stats: { chapters: 18, branches: 7, avgRating: 3.7 },

    coverImage: '',
    description: '',
    totalChapters: 18,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 3,
    title: 'The Silent Orchard',
    slug: 'the-silent-orchard',
    lastEdited: '2024-07-14',
    isPublic: true,
    status: 'published',
    rating: 'MATURE',
    genres: ['Horror', 'Mystery'],
    stats: { chapters: 9, branches: 3, avgRating: 4.0 },

    coverImage: '',
    description: '',
    totalChapters: 9,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 4,
    title: 'Chronicles of Silverwind',
    slug: 'chronicles-of-silverwind',
    lastEdited: '2024-07-16',
    isPublic: false,
    status: 'in_review',
    rating: 'GENERAL',
    genres: ['Fantasy'],
    stats: { chapters: 22, branches: 5, avgRating: 4.5 },

    coverImage: '',
    description: '',
    totalChapters: 22,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 5,
    title: 'Neon Skies',
    slug: 'neon-skies',
    lastEdited: '2024-07-18',
    isPublic: true,
    status: 'published',
    rating: 'TEEN',
    genres: ['Sci-Fi', 'Romance'],
    stats: { chapters: 11, branches: 2, avgRating: 3.9 },

    coverImage: '',
    description: '',
    totalChapters: 11,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 6,
    title: 'Ashes of the Phoenix',
    slug: 'ashes-of-the-phoenix',
    lastEdited: '2024-07-20',
    isPublic: false,
    status: 'draft',
    rating: 'MATURE',
    genres: ['Action', 'Fantasy'],
    stats: { chapters: 15, branches: 6, avgRating: 4.1 },

    coverImage: '',
    description: '',
    totalChapters: 15,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 7,
    title: 'The Moonlit Paradox',
    slug: 'the-moonlit-paradox',
    lastEdited: '2024-07-22',
    isPublic: true,
    status: 'published',
    rating: 'GENERAL',
    genres: ['Mystery', 'Romance'],
    stats: { chapters: 8, branches: 2, avgRating: 3.4 },

    coverImage: '',
    description: '',
    totalChapters: 8,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 8,
    title: 'Children of the Iron Star',
    slug: 'children-of-the-iron-star',
    lastEdited: '2024-07-24',
    isPublic: false,
    status: 'in_review',
    rating: 'TEEN',
    genres: ['Sci-Fi', 'Action'],
    stats: { chapters: 19, branches: 8, avgRating: 4.6 },

    coverImage: '',
    description: '',
    totalChapters: 19,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 9,
    title: 'Garden of Whispers',
    slug: 'garden-of-whispers',
    lastEdited: '2024-07-26',
    isPublic: true,
    status: 'published',
    rating: 'MATURE',
    genres: ['Horror', 'Fantasy'],
    stats: { chapters: 6, branches: 1, avgRating: 3.8 },

    coverImage: '',
    description: '',
    totalChapters: 6,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
  {
    id: 10,
    title: 'Echoes in the Deep Blue',
    slug: 'echoes-in-the-deep-blue',
    lastEdited: '2024-07-28',
    isPublic: false,
    status: 'draft',
    rating: 'GENERAL',
    genres: ['Adventure', 'Action'],
    stats: { chapters: 14, branches: 4, avgRating: 4.3 },

    coverImage: '',
    description: '',
    totalChapters: 14,
    totalReads: 0,
    totalVotes: 0,
    uniqueContributors: 0,

    settings: {
      allowBranching: true,
      requireApproval: false,
      allowComments: true,
      allowVoting: true,
    },
  },
];
