import type { Request } from '@/type/flow.type';

export const submitRequest: Request[] = [
  {
    id: '1',
    title: 'Add Gojo’s Past Chapter',
    storyTitle: 'The Jujutsu Legacy',
    chapterName: 'Gojo’s Origins',
    description:
      'Explores Gojo’s childhood and early mastery of Limitless before joining Jujutsu High.',
    changeType: 'new',
    author: { name: 'Gojo Saturo', avatar: '/avatars/gojo.png' },
    contributors: ['Nanami Kento'],
    timeAgo: '2h ago',
    status: 'open',
    priority: 'high',
    tags: ['character', 'backstory'],
    comments: [
      {
        id: 'c1',
        author: { name: 'Nanami Kento', avatar: '/avatars/nanami.png' },
        content: 'This chapter idea is solid. Consider adding a training montage.',
        timeAgo: '1h ago',
      },
    ],
  },
  {
    id: '2',
    title: 'Revise Dialogue Tone',
    storyTitle: 'The Jujutsu Legacy',
    chapterName: 'Awakening',
    description:
      'Improves character dialogue to match emotional pacing during Yuji’s confrontation.',
    author: { name: 'Megumi Fushiguro', avatar: '/avatars/megumi.png' },
    timeAgo: '1d ago',
    status: 'approved',
    priority: 'medium',
    tags: ['dialogue', 'emotion'],
    changeType: 'update',
  },
  {
    id: '3',
    title: 'Add Flashback Scene',
    storyTitle: 'The Dark Chronicles',
    chapterName: 'Echoes of Night',
    description: 'Adds a flashback revealing the first encounter with the masked entity.',
    author: { name: 'Itadori Yuji', avatar: '/avatars/itadori.png' },
    timeAgo: '3d ago',
    status: 'rejected',
    priority: 'low',
    tags: ['flashback', 'storytelling'],
    changeType: 'update',
    comments: [
      {
        id: 'c2',
        author: { name: 'Suguru Geto', avatar: '/avatars/geto.png' },
        content: 'The flashback disrupts pacing. Shorten it for better flow.',
        timeAgo: '2d ago',
      },
    ],
  },
  {
    id: '4',
    title: 'Expand Ending Monologue',
    storyTitle: 'The Cursed Path',
    chapterName: 'Twilight’s Edge',
    description: 'Extends the ending scene to emphasize moral contrast and inner conflict.',
    author: { name: 'Nobara Kugisaki', avatar: '/avatars/nobara.png' },
    contributors: ['Maki Zenin'],
    timeAgo: '6h ago',
    status: 'open',
    priority: 'high',
    tags: ['ending', 'character development'],
    changeType: 'update',
  },
  {
    id: '5',
    title: 'Add Background Lore',
    storyTitle: 'The Celestial Mirror',
    chapterName: 'The Silver Gate',
    description: 'Introduces historical context of the Mirror Realm for upcoming arcs.',
    author: { name: 'Toge Inumaki', avatar: '/avatars/toge.png' },
    timeAgo: '2d ago',
    status: 'merged',
    priority: 'medium',
    tags: ['lore', 'worldbuilding'],
    changeType: 'new',
  },
  {
    id: '6',
    title: 'Fix Timeline Inconsistency',
    storyTitle: 'Chronicles of Dawn',
    chapterName: 'Broken Time',
    description: 'Corrects event order and adds transitions between battle and aftermath.',
    author: { name: 'Yuta Okkotsu', avatar: '/avatars/yuta.png' },
    timeAgo: '12h ago',
    status: 'approved',
    priority: 'high',
    tags: ['timeline', 'consistency'],
    changeType: 'update',
  },
  {
    id: '7',
    title: 'Add Character Introduction',
    storyTitle: 'Whispers of Fate',
    chapterName: 'The First Whisper',
    description: 'Introduces a mysterious figure hinted in previous chapters.',
    author: { name: 'Maki Zenin', avatar: '/avatars/maki.png' },
    timeAgo: '4d ago',
    status: 'open',
    priority: 'medium',
    tags: ['character', 'foreshadowing'],
    changeType: 'new',
  },
  {
    id: '8',
    title: 'Rewrite Final Battle Scene',
    storyTitle: 'The Shadow War',
    chapterName: 'The Last Stand',
    description: 'Rewrites the climactic fight for better pacing and balance between protagonists.',
    author: { name: 'Suguru Geto', avatar: '/avatars/geto.png' },
    contributors: ['Gojo Saturo'],
    timeAgo: '5d ago',
    status: 'rejected',
    priority: 'high',
    tags: ['battle', 'climax'],
    changeType: 'update',
  },
  {
    id: '9',
    title: 'Add Alternate Ending',
    storyTitle: 'The Jujutsu Legacy',
    chapterName: 'Fading Light',
    description: 'Introduces an alternate ending branch where Yuji sacrifices himself.',
    author: { name: 'Itadori Yuji', avatar: '/avatars/itadori.png' },
    timeAgo: '8h ago',
    status: 'open',
    priority: 'high',
    tags: ['ending', 'alternate'],
    changeType: 'new',
  },
  {
    id: '10',
    title: 'Grammar and Formatting Fix',
    storyTitle: 'Whispers of Fate',
    chapterName: 'The First Whisper',
    description: 'Fixes typos and paragraph spacing for improved readability.',
    author: { name: 'Shoko Ieiri', avatar: '/avatars/shoko.png' },
    timeAgo: '6d ago',
    status: 'merged',
    priority: 'low',
    tags: ['grammar', 'formatting'],
    changeType: 'update',
  },
  {
    id: '11',
    title: 'Introduce New Villain Arc',
    storyTitle: 'The Dark Chronicles',
    chapterName: 'Shadow Rising',
    description: 'Adds a new antagonist with a mysterious agenda.',
    author: { name: 'Suguru Geto', avatar: '/avatars/geto.png' },
    contributors: ['Itadori Yuji'],
    timeAgo: '7h ago',
    status: 'open',
    priority: 'high',
    tags: ['villain', 'arc'],
    changeType: 'new',
  },
  {
    id: '12',
    title: 'Scene Transition Enhancement',
    storyTitle: 'Chronicles of Dawn',
    chapterName: 'Dawn Break',
    description: 'Adds smoother transitions between action and dialogue scenes.',
    author: { name: 'Yuta Okkotsu', avatar: '/avatars/yuta.png' },
    timeAgo: '10h ago',
    status: 'approved',
    priority: 'medium',
    tags: ['scene', 'transition'],
    changeType: 'update',
  },
  {
    id: '13',
    title: 'Improve Foreshadowing',
    storyTitle: 'The Celestial Mirror',
    chapterName: 'Mirror Shards',
    description: 'Adds subtle hints about upcoming plot twists.',
    author: { name: 'Toge Inumaki', avatar: '/avatars/toge.png' },
    timeAgo: '3d ago',
    status: 'open',
    priority: 'medium',
    tags: ['foreshadowing', 'plot'],
    changeType: 'update',
  },
  {
    id: '14',
    title: 'Revamp Opening Chapter',
    storyTitle: 'The Shadow War',
    chapterName: 'Dawn of Conflict',
    description: 'Rewrites the opening chapter to hook readers faster.',
    author: { name: 'Megumi Fushiguro', avatar: '/avatars/megumi.png' },
    timeAgo: '1d ago',
    status: 'merged',
    priority: 'high',
    tags: ['opening', 'storytelling'],
    changeType: 'update',
  },
  {
    id: '15',
    title: 'Add Comic Relief Scene',
    storyTitle: 'The Jujutsu Legacy',
    chapterName: 'Light in Darkness',
    description: 'Inserts a humorous scene to relieve tension before the climax.',
    author: { name: 'Nobara Kugisaki', avatar: '/avatars/nobara.png' },
    timeAgo: '5h ago',
    status: 'open',
    priority: 'low',
    tags: ['humor', 'tone'],
    changeType: 'new',
  },
  {
    id: '16',
    title: 'Character Skill Development',
    storyTitle: 'Whispers of Fate',
    chapterName: 'Awakening Powers',
    description: 'Shows character growth and new abilities emerging.',
    author: { name: 'Maki Zenin', avatar: '/avatars/maki.png' },
    timeAgo: '2d ago',
    status: 'approved',
    priority: 'medium',
    tags: ['skill', 'development'],
    changeType: 'update',
  },
  {
    id: '17',
    title: 'Adjust Story Pacing',
    storyTitle: 'Chronicles of Dawn',
    chapterName: 'Momentum Shift',
    description: 'Tightens pacing for smoother reading experience.',
    author: { name: 'Yuta Okkotsu', avatar: '/avatars/yuta.png' },
    timeAgo: '8h ago',
    status: 'approved',
    priority: 'high',
    tags: ['pacing', 'flow'],
    changeType: 'update',
  },
  {
    id: '18',
    title: 'Add Hidden Easter Egg',
    storyTitle: 'The Dark Chronicles',
    chapterName: 'Secret Passage',
    description: 'Includes a hidden reference for attentive readers.',
    author: { name: 'Itadori Yuji', avatar: '/avatars/itadori.png' },
    timeAgo: '1d ago',
    status: 'merged',
    priority: 'low',
    tags: ['easter egg', 'fun'],
    changeType: 'new',
  },
  {
    id: '19',
    title: 'Dialogue Consistency Fix',
    storyTitle: 'The Celestial Mirror',
    chapterName: 'Reflections',
    description: 'Ensures all characters maintain consistent voice throughout the chapter.',
    author: { name: 'Toge Inumaki', avatar: '/avatars/toge.png' },
    timeAgo: '6h ago',
    status: 'approved',
    priority: 'medium',
    tags: ['dialogue', 'consistency'],
    changeType: 'update',
  },
  {
    id: '20',
    title: 'Add Foreshadowing to Ending',
    storyTitle: 'The Shadow War',
    chapterName: 'Final Countdown',
    description: 'Adds hints about the final twist in the last chapter.',
    author: { name: 'Suguru Geto', avatar: '/avatars/geto.png' },
    timeAgo: '4h ago',
    status: 'open',
    priority: 'high',
    tags: ['foreshadowing', 'ending'],
    changeType: 'update',
  },
];
