import type { LeaderboardUser, TopStory, TopContributor } from './leaderboard.types';

export const mockTopWriters: LeaderboardUser[] = [
  {
    id: '1',
    rank: 1,
    username: 'fantasy_master',
    displayName: 'Elena Rivers',
    avatarUrl: 'https://i.pinimg.com/736x/4c/ab/77/4cab77de6b83b7e3149ce03867194ea5.jpg',
    stats: {
      totalReads: 1250000,
      storiesWritten: 12,
      chaptersContributed: 156,
      upvotesReceived: 89500,
    },
    badges: [
      { id: '1', name: 'Top Writer', icon: '👑', color: 'amber' },
      { id: '2', name: 'Prolific', icon: '✍️', color: 'purple' },
    ],
    rankChange: 0,
  },
  {
    id: '2',
    rank: 2,
    username: 'mystery_weaver',
    displayName: 'James Chen',
    avatarUrl: 'https://i.pinimg.com/474x/33/fb/eb/33fbeb45315109aa81ed6a7d1551552c.jpg',
    stats: {
      totalReads: 980000,
      storiesWritten: 8,
      chaptersContributed: 124,
      upvotesReceived: 72300,
    },
    badges: [{ id: '3', name: 'Rising Star', icon: '⭐', color: 'blue' }],
    rankChange: 2,
  },
  {
    id: '3',
    rank: 3,
    username: 'scifi_dreamer',
    displayName: 'Sarah Kim',
    avatarUrl: 'https://i.pravatar.cc/150?u=sarah',
    stats: {
      totalReads: 875000,
      storiesWritten: 6,
      chaptersContributed: 98,
      upvotesReceived: 65200,
    },
    badges: [{ id: '4', name: 'Innovator', icon: '🚀', color: 'pink' }],
    rankChange: -1,
  },
  {
    id: '4',
    rank: 4,
    username: 'romance_queen',
    displayName: 'Maria Garcia',
    avatarUrl: 'https://i.pravatar.cc/150?u=maria',
    stats: {
      totalReads: 720000,
      storiesWritten: 15,
      chaptersContributed: 210,
      upvotesReceived: 58900,
    },
    badges: [],
    rankChange: 1,
  },
  {
    id: '5',
    rank: 5,
    username: 'thriller_king',
    displayName: 'David Park',
    avatarUrl: 'https://i.pravatar.cc/150?u=david',
    stats: {
      totalReads: 650000,
      storiesWritten: 4,
      chaptersContributed: 67,
      upvotesReceived: 48500,
    },
    badges: [{ id: '5', name: 'Fan Favorite', icon: '❤️', color: 'red' }],
    rankChange: 3,
    isCurrentUser: true,
  },
  {
    id: '6',
    rank: 6,
    username: 'horror_tales',
    displayName: 'Alex Morgan',
    avatarUrl: 'https://i.pravatar.cc/150?u=alex',
    stats: {
      totalReads: 580000,
      storiesWritten: 7,
      chaptersContributed: 89,
      upvotesReceived: 42100,
    },
    badges: [],
    rankChange: -2,
  },
  {
    id: '7',
    rank: 7,
    username: 'adventure_seeker',
    displayName: 'Chris Lee',
    avatarUrl: 'https://i.pravatar.cc/150?u=chris',
    stats: {
      totalReads: 520000,
      storiesWritten: 5,
      chaptersContributed: 72,
      upvotesReceived: 38700,
    },
    badges: [],
    rankChange: 0,
  },
  {
    id: '8',
    rank: 8,
    username: 'comedy_writer',
    displayName: 'Emma Wilson',
    avatarUrl: 'https://i.pravatar.cc/150?u=emma',
    stats: {
      totalReads: 480000,
      storiesWritten: 9,
      chaptersContributed: 145,
      upvotesReceived: 35200,
    },
    badges: [],
    rankChange: 1,
  },
  {
    id: '9',
    rank: 9,
    username: 'drama_artist',
    displayName: 'Michael Brown',
    avatarUrl: 'https://i.pravatar.cc/150?u=michael',
    stats: {
      totalReads: 420000,
      storiesWritten: 3,
      chaptersContributed: 48,
      upvotesReceived: 31500,
    },
    badges: [],
    rankChange: -1,
  },
  {
    id: '10',
    rank: 10,
    username: 'slice_of_life',
    displayName: 'Lisa Taylor',
    avatarUrl: 'https://i.pravatar.cc/150?u=lisa',
    stats: {
      totalReads: 380000,
      storiesWritten: 6,
      chaptersContributed: 82,
      upvotesReceived: 28900,
    },
    badges: [],
    rankChange: 2,
  },
];

export const mockTopStories: TopStory[] = [
  {
    id: '1',
    rank: 1,
    title: 'The Dragon Chronicles',
    slug: 'dragon-chronicles',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    author: {
      username: 'fantasy_master',
      avatarUrl: 'https://i.pinimg.com/736x/4c/ab/77/4cab77de6b83b7e3149ce03867194ea5.jpg',
    },
    stats: {
      reads: 450000,
      chapters: 47,
      rating: 4.9,
      subscribers: 12500,
    },
    genre: 'Fantasy',
    rankChange: 0,
  },
  {
    id: '2',
    rank: 2,
    title: 'Midnight Detective',
    slug: 'midnight-detective',
    coverUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400',
    author: {
      username: 'mystery_weaver',
      avatarUrl: 'https://i.pinimg.com/474x/33/fb/eb/33fbeb45315109aa81ed6a7d1551552c.jpg',
    },
    stats: {
      reads: 380000,
      chapters: 35,
      rating: 4.8,
      subscribers: 9800,
    },
    genre: 'Mystery',
    rankChange: 1,
  },
  {
    id: '3',
    rank: 3,
    title: 'Stars Beyond',
    slug: 'stars-beyond',
    coverUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400',
    author: {
      username: 'scifi_dreamer',
      avatarUrl: 'https://i.pravatar.cc/150?u=sarah',
    },
    stats: {
      reads: 320000,
      chapters: 28,
      rating: 4.7,
      subscribers: 8200,
    },
    genre: 'Sci-Fi',
    rankChange: -1,
  },
  {
    id: '4',
    rank: 4,
    title: 'Hearts Intertwined',
    slug: 'hearts-intertwined',
    coverUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=400',
    author: {
      username: 'romance_queen',
      avatarUrl: 'https://i.pravatar.cc/150?u=maria',
    },
    stats: {
      reads: 290000,
      chapters: 52,
      rating: 4.6,
      subscribers: 7500,
    },
    genre: 'Romance',
    rankChange: 2,
  },
  {
    id: '5',
    rank: 5,
    title: 'The Last Heist',
    slug: 'last-heist',
    coverUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400',
    author: {
      username: 'thriller_king',
      avatarUrl: 'https://i.pravatar.cc/150?u=david',
    },
    stats: {
      reads: 250000,
      chapters: 24,
      rating: 4.8,
      subscribers: 6800,
    },
    genre: 'Thriller',
    rankChange: 0,
  },
];

export const mockTopContributors: TopContributor[] = [
  {
    id: '1',
    rank: 1,
    username: 'branch_master',
    avatarUrl: 'https://i.pravatar.cc/150?u=branch1',
    contributions: 245,
    storiesContributed: 18,
    acceptanceRate: 92,
    rankChange: 0,
  },
  {
    id: '2',
    rank: 2,
    username: 'story_helper',
    avatarUrl: 'https://i.pravatar.cc/150?u=branch2',
    contributions: 198,
    storiesContributed: 24,
    acceptanceRate: 88,
    rankChange: 1,
  },
  {
    id: '3',
    rank: 3,
    username: 'creative_mind',
    avatarUrl: 'https://i.pravatar.cc/150?u=branch3',
    contributions: 176,
    storiesContributed: 15,
    acceptanceRate: 95,
    rankChange: -1,
  },
  {
    id: '4',
    rank: 4,
    username: 'plot_twister',
    avatarUrl: 'https://i.pravatar.cc/150?u=branch4',
    contributions: 154,
    storiesContributed: 12,
    acceptanceRate: 85,
    rankChange: 3,
  },
  {
    id: '5',
    rank: 5,
    username: 'chapter_pro',
    avatarUrl: 'https://i.pravatar.cc/150?u=branch5',
    contributions: 132,
    storiesContributed: 20,
    acceptanceRate: 78,
    rankChange: -2,
  },
];
